name: Coelacanth Sound
favicon: null
layout_spectrum: 0.9213000694289804
typography_spectrum: 0.05626244400627911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6060352243948728
  lightness: 0.796333358855918
  saturation: 0.9188033803366125
  rhythmicContrast: 0.051910152891650796
purpose: []
